name: Deploy Docker Network1

on:
  push:
    branches:
      - main  # Adjust to the branch you want to trigger the workflow

jobs:
  deploy-network:
    runs-on: self-hosted
    environment: vm

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Make Deployment Script Executable
      - name: Make Deployment Script Executable
        run: chmod +x ./bridge_network_create.sh

      # Step 3: Run the Deployment Script
      - name: Deploy Docker Network
        env:
          SSH_PASSWORD: ${{ secrets.VM }}
        run: bash ./bridge_network_create.sh "$SSH_PASSWORD"

      # Step 4: Make Bash script executable
      - name: Make Bash script executable
        run: chmod +x deploy_python_container.sh

      # Step 5: Run Bash script
      - name: Deploy to Slave VM
        env:
          SSH_PASSWORD: ${{ secrets.VM }}
        run: bash ./deploy_python_container.sh "$SSH_PASSWORD"
