name: Deploy Docker Network 

on:
  push:
    branches:
      - main  # Adjust as per your branch

jobs:
  deploy-network:
    runs-on: self-hosted
    environment: vm

    steps:
      # Step 1: Checkout Code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Make Scripts Executable
      - name: Make Scripts Executable
        run: chmod +x ./create_docker_network.py ./bridge_network_create.sh

      # Step 3: Execute Bash Script to Upload and Execute Python Script
      - name: Deploy Docker Bridge Network
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: bash ./bridge_network_create.sh "$SSH_PASSWORD"
