name: Deploy Docker Network

on:
  push:
    branches:
      - main  # Adjust to the branch you want to trigger the workflow

jobs:
  deploy-network:
    runs-on: self-hosted
    environment: vm

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Make Scripts Executable
      - name: Make Scripts Executable
        run: chmod +x ./deploy_docker_network.sh

      # Step 3: Run the Deployment Script
      - name: Deploy Docker Network
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: bash ./deploy_docker_network.sh "$SSH_PASSWORD"
