name: Deploy Docker Network1

on:
  push:
    branches:
      - main  # Adjust to the branch you want to trigger the workflow

jobs:
  deploy-network:
    runs-on: self-hosted
    environment: vm

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Make Scripts Executable
      - name: Make Deployment Script Executable
        run: chmod +x ./bridge_network_create.sh

      # Step 3: Run the Deployment Script
      - name: Deploy Docker Network
        env:
          SSH_PASSWORD: ${{ vm.SSH_PASSWORD }}
        run: bash ./bridge_network_create.sh "$SSH_PASSWORD"
